### ISSUE TITLE
Rounding error

### ISSUE THREAD

**Issue by quakemmo** [lessmore92/base-x#1]
```Implicit conversion from float 25.164171604901235 to int loses precision in /<stripped>/ripple/BaseX.php on line 195```

This happens when trying to validate a classic Ripple address through your ripple php library php-ripple-address-codec. My app uses bcscale to add decimals to bc* functions, not sure this is relevant.

**Comment by lessmore92** [comment]
Sorry for the delay in getting back to you.
Can provide more information and sample, to regenerate the error?
What version of PHP is used?

**Comment by quakemmo** [comment]
PHP 8.1

```
<?php declare(strict_types=1);

error_reporting(E_ALL);

require 'BaseX.php';
require 'Buffer.php';
require 'CodecWithXrpAlphabet.php';
require 'RippleAddressCodec.php';

$a = 'raMByQGTYwtmtFWiMCXRsK8xAWWJqUXEtb';

$api = new \Lessmore92\RippleAddressCodec\RippleAddressCodec();
if (!$api->isValidClassicAddress($a)) {
    echo "Not good\n";
} else {
   echo "Good\n";
}
```

**Comment by lessmore92** [comment]
> PHP 8.1
> 
> ```
> <?php declare(strict_types=1);
> 
> error_reporting(E_ALL);
> 
> require 'BaseX.php';
> require 'Buffer.php';
> require 'CodecWithXrpAlphabet.php';
> require 'RippleAddressCodec.php';
> 
> $a = 'raMByQGTYwtmtFWiMCXRsK8xAWWJqUXEtb';
> 
> $api = new \Lessmore92\RippleAddressCodec\RippleAddressCodec();
> if (!$api->isValidClassicAddress($a)) {
>     echo "Not good\n";
> } else {
>    echo "Good\n";
> }
> ```

I checked this code and it worked perfectly.
Please make sure you are using the latest version of `php-ripple-address-codec`.

**Comment by quakemmo** [comment]
Have you checked it with error_reporting(E_ALL) ?

**Comment by lessmore92** [comment]
> Have you checked it with error_reporting(E_ALL) ?

Yes

**Comment by quakemmo** [comment]
Was it with PHP 8.1 ?
https://php.watch/versions/8.1/deprecate-implicit-conversion-incompatible-float-string

I've just double checked again. Getting the warning.
Not meaning to harass you by any means!

**Comment by lessmore92** [comment]
Oh, yes I see that.
I think it needs a simple change; cast to int `$a = (int)$a;` on method `unsignedRightShift` of `BaseX` .
Such as this:

```
...
    private function unsignedRightShift($a, $b)
    {
        $a = (int)$a;
...
```
Please share your thoughts with me about this and its possible side effects.

**Comment by quakemmo** [comment]
I cannot comment on your casting suggestion as I do not have a deep understanding of your code and wouldn't like to help introducing obscure bugs.

I would recommend you go through all your code and strongly type whatever can be typed:

```
function blah(string $str, int $str): bool {

}
```


There's a great IDE called PHPStorm that helps with this stuff immensely.
They can give you a free license if you point them to your github account proving that you are using it for opensource projects.

**Comment by quakemmo** [comment]
Also check out PHP 7, 8 and 8.1 features - they help making code more robust and readable.

In PHPStorm, set your PHP version to 8.1 and just work from there until you have no errors / warnings after running "Inspect code".

It will take you a few hours to get accustomed to the IDE, but it's a priceless addition to your toolbox, even if you don't use it to actually write code.

I write PHP code in vim, and every once in a while fire up PHPStorm just for code inspection. It helped me catch COUNTLESS bugs, especially in rare code paths that would have never been caught otherwise.

**Comment by diadal** [comment]
@quakemmo were you able to fix this

**Comment by lessmore92** [comment]
fixed in https://github.com/lessmore92/base-x/pull/2
thanks to all
